### ISSUE TITLE
Medicine Production

### ISSUE THREAD

**Issue by Chooper8** [skyarkhangel/CombatRealism#25]
While mod is on you can produce any drug except medicine

**Comment by Ryuusenka** [comment]
Same issue here...
Researched drug prod. and microelectronic bas. and nothing on drug lab.
Researched everything on god dev mod, and nothing.
800 neutramines on stock on my colony waiting to evolve in to a glorious medicine lol

**Comment by Thorbane** [comment]
It's a XML bug, the recipe is defined in the stock Medicine def, but CR overwrites it.

**Comment by Chooper8** [comment]
Any fix for it?

**Comment by skyarkhangel** [comment]
Fixed in last update.
