### ISSUE TITLE
A16U Building walls and doors takes no time

### ISSUE THREAD

**Issue by Fafn1r** [skyarkhangel/CombatRealism#28]
Pawns build walls and doors by delivering materials and then just touching them - they get constructed instantly.

**Comment by Thorbane** [comment]
Looks like the WorkToBuild def is not defined in the Def file.

**Comment by Thorbane** [comment]
Should be fixed in the latest release.

**Comment by Fafn1r** [comment]
Yeah, I noticed the change. Pawns are still building too fast though, I don't know if it's due to incorrect WorkToMake or changes to pawn work speed.

**Comment by skyarkhangel** [comment]
Fixed.
