### ISSUE TITLE
Repeating request's for a bad reference causing fps death

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/CombatRealism#30]
I'm using commit cadf7bae08b5b52205a1f154a6edb8642c85a68e

Edit: The said animals are unable to attack. (They're all hunting or trying too)

![error](https://cloud.githubusercontent.com/assets/5264667/21373487/457e7f14-c717-11e6-959d-efa7aa7280e6.jpg)

**Comment by skyarkhangel** [comment]
ok

**Comment by skyarkhangel** [comment]
Please, test with latest release version (not from master tree!)

**Comment by zakhad** [comment]
It's a bit of a weird bug, first 3 minutes into the game I'm able to melee a rat to death with the first 2 attacks (Naked fist punching :p) everything is working fine so far...

2 in game days later I get a maddened rat (Psychic  event) (Are maddened animals effected differently?) 
I'm unable to hit it, (I'm using the same naked fist punching) and I get the following error very similar to the one above

![error2](https://cloud.githubusercontent.com/assets/5264667/21409242/09d03ca4-c7d1-11e6-97f7-8518ca2a9345.jpg)

I'm not using the "release version" I'm using 1 commit ahead of it since there were no further changes to the animal fix that you have committed. (I assumed that this wouldn't cause any conflicting results and I could also report if the fixes thorbane implemented had worked on)

Fixed explosives not exploding - Thorbane commit 4542ff2b1eb07d2db51dc7c8892099780984a97d

**Comment by zakhad** [comment]
To clarify using the stable version seems to have fixed it so far.

**Comment by zakhad** [comment]
Update fixed it  no relapse, closing.
