### ISSUE TITLE
Clothing in inventory behaves strangely

### ISSUE THREAD

**Issue by duncanburke** [skyarkhangel/CombatRealism#46]
Clothing is immediately and automatically dropped or hauled to a stockpile when picked up into the inventory.

When a drafted colonist picks up clothing, instructing it to drop the clothing has no effect.

This is non-critical, but it merits further investigation.

### Steps to reproduce:

1. Start a new colony
2. Select a colonist, tell them to drop their jacket
    The jacket is dropped on the ground and marked as forbidden.
3. Tell the colonist to pick up the jacket
    The jacket is immediately dropped back on the ground
4. Draft the colonist, tell them to pick up the jacket
    The jacket appears in the inventory
5. Tell the colonist to drop the jacket
    The colonist briefly gets the job "Removing synthread jacket (normal)", the jacket stays in the inventory
6. Undraft the colonist
    The jacket is immediately dropped
7. Create a stockpile, tell the colonist to pick up the jacket
    The jacket is picked up, dropped, picked up again, and hauled to the stockpile
8. Draft the colonist, tell them to pick up the jacket, and move them away from the stockpile
    The jacket is picked up and stays in the inventory
9. Undraft the colonist
    The jacket is dropped, picked up again and hauled to the stockpile

**Comment by skyarkhangel** [comment]
Fixed
