### ISSUE TITLE
Weight modifiers do not apply to caravan capacity.

### ISSUE THREAD

**Issue by Vek17** [skyarkhangel/CombatRealism#48]
The new Rimworld inventory system and the CR inventory system do not seem to properly interact. A pawn in power armor still has a caravan capacity of 35kg despite the 60kg carry weight buff granted by the armor.

**Comment by duncanburke** [comment]
Okay, I've reproduced this and am working on it. Looks like it's a matter of patching `RimWorld.MassUtility.Capacity`.
