### ISSUE TITLE
Drug policies not working.

### ISSUE THREAD

**Issue by Thorbane** [skyarkhangel/CombatRealism#52]
Tested with only CR and Core enabled.  Pawns will only use drugs if commanded or for social use.  Pawns will not take drugs for an addiction, on a schedule, or take drugs to their inventory.

**Comment by duncanburke** [comment]
It looks like the consume button is only available for food, not drugs, in Core. I've confirmed that it's not present in CR. Do you want me to look into it, or are you investigating it yourself?

**Comment by Thorbane** [comment]
Please do.  I have no idea what I'm doing when it comes to the AI.

**Comment by duncanburke** [comment]
Oops, I commented in the wrong issue. Sorry about that. I'll see what I can do with this one, but what I was actually asking was whether you're working on issue #53.

**Comment by Fafn1r** [comment]
Does it work if you add drugs to their loadouts as well as forcing them to carry them with drug policies?

**Comment by Thorbane** [comment]
Ah.  <li Class="JobGiver_TakeDrugsForDrugPolicy"/> was missing from the CR edited thinkTree.  That's probably it
