### ISSUE TITLE
Issue or feature? Turrets can't shoot from behind sandbags

### ISSUE THREAD

**Issue by frenchiveruti** [skyarkhangel/CombatRealism#69]
I don't really know what is the issue here, but it seems that the sandbags are considered a full wall and the auto-turrets won't fire from behind them. Is this on purpose or a bug?

**Comment by carpediembr** [comment]
sandbags and embrasures for me.

**Comment by frenchiveruti** [comment]
Yeah, embrasures too present this problem, but for example manned weapons such as the KPV can shoot through them.

**Comment by skyarkhangel** [comment]
seems fixed in next update.
